[project]
name = "rag-datakit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "distilabel[openai]>=1.5.3",
    "pillow>=11.3.0",
]
